
name: Update Coinection Seed

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update-seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Open Coin Data
        uses: actions/checkout@v4
        with:
          repository: coinection/open-coin-data
          path: ocd

      - name: Checkout Data Converter
        uses: actions/checkout@v4
        with:
          repository: coinection/data-converter
          path: data-converter
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Print repository content 1
        run: |
          ls -la /home/runner/work/Open-Coin-Data

      - name: Print repository content 2
        run: |
          ls -la /home/runner/work/Open-Coin-Data/Open-Coin-Data

      - name: Run Data Converter
        run: |
          cd /data-converter
          npm install
          npm run start "./ocd"

      - name: Print folder content
        run: |
          ls -la /ocd
          
          